### ISSUE TITLE
When closing main window, Timeit disappears but is left running, (Unity with indicators)

### ISSUE THREAD

**Issue by hackel** [Hoglet/TimeIT#7] opened 2015-03-30 18:19 UTC
When I close Timeit, even by explicitly choosing Quit from the File menu, the window closes but Timeit stays running.  I cannot launch a new instance, and have to find it's pid and kill it manually.  Running Timeit 1.9.9.18 on Ubuntu 14.10.

**Comment by Hoglet** [comment] 2015-03-30 18:25
It is working for me so I will need more info to solve. Could you first update to latest version and see if problem persists. If so I could try with your database, if it is not containing sensitive data.

**Comment by Hoglet** [comment] 2015-03-31 09:43
Are you syncing to a TimeIT-Server? I suspect that it is the sync thread that does not terminate.

**Comment by hackel** [comment] 2015-04-01 08:00
Nope, not using sync yet.  I just tried exiting it again, and it is now exiting fine when I explicitly choose Quit from the File menu, but not when I close it by pressing the window X.  It is acting as if it is trying to hide itself as if there were an indicator applet or some other way to reveal it.  If so, I am not seeing any indicator.

**Comment by Hoglet** [comment] 2015-04-01 08:12
It is minimizing to systray. If i remember correct you will find the systray hidden(!) in the dropdown on top.  The rationale is that it is suposed to run in the background, automatically track time. The window is not the application.

I guess it is time to implement indicator support...

We leave this open until you feel certain that it works as designed.

**Comment by Hoglet** [comment] 2015-04-01 08:13
Opened a new issue https://github.com/Hoglet/TimeIT/issues/11

**Comment by Hoglet** [comment] 2015-04-01 12:29
Workaround: move status tray applet next to the indicator applet.

**Comment by Hoglet** [comment] 2015-04-07 13:07
It seems like unity is not showing apps in systray if they are not whitelisted, see: http://www.howtogeek.com/68119/how-to-bring-app-icons-back-into-unitys-system-tray/
If this is still true it could be the root of your problem.

According to another post I get the suspicion that the white listing is removed(!).
http://askubuntu.com/questions/362135/how-to-re-enable-tray-icons-for-applications-in-ubuntu-13-10

This sounds insane to me so I might be wrong.

**Comment by Hoglet** [comment] 2015-04-07 15:02
I can confirm that systray is there and is blacklisting everything.

Workaround is to enable white listing again, instructions here: http://www.webupd8.org/2013/05/how-to-get-systray-whitelist-back-in.html

**Comment by hackel** [comment] 2015-04-07 17:49
Thanks for looking all that up for me.  I was aware of that issue, and I really don't want to deal with recompiling Unity just to add back that functionality.  The old systray specification is deprecated, and that's why it was finally removed from Unity after many years.

From the GTK3 docs: "GtkStatusIcon has been deprecated in 3.14. You should consider using notifications or more modern platform-specific APIs instead."

**Comment by Hoglet** [comment] 2015-04-07 18:09
Yes, Gnome and Unity people have some grievances with how the system tray have been used and wants to force everybody into doing what they think is right.
Personally I think the indicator concept is immensely irritating as it forces you to several clicks to open the application window for the music player or mail program and even more to get to the menus. 

I have taken away the indicators from my system as I feel that the old way was much easier to work with. They had good intentions but...

**Comment by Hoglet** [comment] 2015-04-07 18:12
Planned solution to this problem is to make TimeIT open the main window if called while already running. Support for indicator is handled in #11 and is is postponed to a later version.

**Comment by hackel** [comment] 2015-04-07 22:07
Sounds like a good solution.  What about also adding an option whether closing should exit or minimize to the tray?

**Comment by Hoglet** [comment] 2015-04-07 22:16
Closing the application is causing the timers to stop counting so it is not a good choice. Refactoring for counting time while application is off is opening a big can of worms which i am not willing to do.

**Comment by elgod** [comment] 2015-07-27 13:48
Thank you for your great work about TimeIT. I found it when looked for such software which can count multiple tasks simultaniously. I really need option to be able to count time for running tasks even when the application is closed and when is realuanched to add the time to the active tasks.
Thank you for your time!

**Comment by elgod** [comment] 2015-07-27 13:51
Thank you for your great work about TimeIT. I found it when looked for such software which can count multiple tasks simultaniously. I really need option to be able to count time for running tasks even when the application is closed and when is realuanched to add the time to the active tasks.
Also would be nice if able to export/import the data.
Thank you for your time!

**Comment by Hoglet** [comment] 2015-07-27 13:58
Thanks for the support.

The application will not be able to count time when switched off. It is able to count time without any window occupying the screen estate which I suspect is enough for you also.

This bug is about behaviour in Ubuntu (unity). If you have any suggestions then feel free to open a new ticket where you describe the wanted behaviour. 

If using the TimeIT client together with the TimeIT server (https://github.com/Hoglet/TimeIT-Server) then you have the data presented in reports. Raw data can be taken through the REST interface of the server although this is not documented.

**Comment by Hoglet** [comment] 2015-07-27 14:02
And I should maybe also notify that even though this issue has been on hold for several months it is the number one priority and will be taken care of soon. I got stuck with choice of DBus implementation, motivation and real life.....

**Comment by elgod** [comment] 2015-07-27 14:02
"It is able to count time without any window occupying the screen estate which I suspect is enough for you also." - This is sweet but I can not track "offline" tasks as is now or measure time after certain event date. Nevermind. Good luck keep going : )

**Comment by Hoglet** [comment] 2015-07-27 14:04
Could you please clarify? You can manually enter new time entries  and change existing, is this what you asked for?

**Comment by elgod** [comment] 2015-07-27 14:42
Well, I simply need to be able to track time since certain date no matter if the application is turned off : )

**Comment by Hoglet** [comment] 2015-07-27 14:44
That sounds like magic... Please open an issue where you can describe how you want it and we can continue discussions there. Every message we are writing are no sent to "hackel" and I doubt that he is interested.

**Closed** 2019-07-17 19:55 UTC
Labels: Bug
